### ISSUE TITLE
'PostgresJsonListingRepository' object has no attribute 'session'

### ISSUE THREAD

**Issue by maximkz561** [pgorecki/python-ddd#14]
when call http get /catalog get this error

File "/Users/maksimkozeev/code/python-ddd/src/modules/catalog/application/query/get_all_listings.py", line 15, in get_all_listings
    queryset = listing_repository.session.query(listing_repository.model)
AttributeError: 'PostgresJsonListingRepository' object has no attribute 'session'

**Comment by pgorecki** [comment]
Fixed in commit 0b8514d723c04616307cd298b5c46d88ea89aa8c
