### ISSUE TITLE
Wrong import

### ISSUE THREAD

**Issue by maximkz561** [pgorecki/python-ddd#15]
**Error**
while poe start get this error:

File "src/api/routers/catalog.py", line 11, in <module>
    from modules.catalog.module import CatalogModule
ImportError: cannot import name 'CatalogModule' from 'modules.catalog.module' (/Users/maksimkozeev/code/python-ddd/src/modules/catalog/module.py)

**Solution**
from modules.catalog.module import CatalogModule has to be change to from modules.catalog import CatalogModule
and file src/modules/catalo/module.py has to be deleted

**Comment by pgorecki** [comment]
fixed in comment c1d24e267dd72fffa5935bb77ab9d754f90e9606
