### ISSUE TITLE
type object 'Container' has no attribute 'iam_module'

### ISSUE THREAD

**Issue by maximkz561** [pgorecki/python-ddd#16]
since https://github.com/pgorecki/python-ddd/issues/15 is fixed got the error below when poe start

File "src/api/routers/iam.py", line 19, in <module>
    module: IdentityAndAccessModule = dependency(Container.iam_module),
AttributeError: type object 'Container' has no attribute 'iam_module'

**Comment by pgorecki** [comment]
fixed in commit c1d24e267dd72fffa5935bb77ab9d754f90e9606
